---SA
CREATE USER OWNER PASSWORD 'owner';
CREATE USER GUEST PASSWORD 'guest';

GRANT ALTER ANY SCHEMA TO OWNER;
CREATE SCHEMA OWNER AUTHORIZATION OWNER;
-------------------------------
---OWNER

CREATE SEQUENCE OWNER.SEQ_ADRES;

CREATE TABLE OWNER.ADRES
(
    ID          INT DEFAULT OWNER.SEQ_ADRES.nextval PRIMARY KEY,
    MIEJSCOWOSC VARCHAR(255) NOT NULL,
    ULICA       VARCHAR(255) NOT NULL,
    NR_LOKALU   VARCHAR(8),
    KOD         VARCHAR(6)
);


------------------------------------------

CREATE SEQUENCE OWNER.SEQ_LISTA_DODATKOW;
CREATE TABLE OWNER.LISTA_DODATKOW
(
    ID    INT DEFAULT OWNER.SEQ_LISTA_DODATKOW.nextval PRIMARY KEY,
    NAZWA VARCHAR(255) NOT NULL
);

-----

CREATE SEQUENCE OWNER.SEQ_RESTAURACJA;
CREATE TABLE OWNER.RESTAURACJA
(
    ID       INT DEFAULT OWNER.SEQ_RESTAURACJA.nextval PRIMARY KEY,
    NAZWA    VARCHAR(400) NOT NULL,
    ID_ADRES INT          NOT NULL,
    H_OTW    TIME(4)      NOT NULL,
    H_ZAM    TIME(4)      NOT NULL,
    DOWOZ    BOOLEAN      NOT NULL
);

ALTER TABLE OWNER.RESTAURACJA
    ADD FOREIGN KEY (ID_ADRES)
        REFERENCES OWNER.ADRES (ID);

-----
CREATE SEQUENCE OWNER.SEQ_MENU;
CREATE TABLE OWNER.MENU
(
    ID             INT DEFAULT OWNER.SEQ_MENU.nextval PRIMARY KEY,
    ID_REST        INT           NOT NULL,
    NAZWA_PRODUKTU VARCHAR(400)  NOT NULL,
    CENA           DECIMAL(5, 2) NOT NULL
);

ALTER TABLE OWNER.MENU
    ADD FOREIGN KEY (ID_REST)
        REFERENCES OWNER.RESTAURACJA (ID);

----
CREATE SEQUENCE OWNER.SEQ_PLATNOSC;
CREATE TABLE OWNER.PLATNOSC
(
    ID               INT DEFAULT OWNER.SEQ_PLATNOSC.nextval PRIMARY KEY,
    ID_REST          INT         NOT NULL,
    RODZAJ_PLATNOSCI VARCHAR(20) NOT NULL
);

ALTER TABLE OWNER.PLATNOSC
    ADD CONSTRAINT PLATNOSC_CONSTRAINT CHECK (RODZAJ_PLATNOSCI in ('gotówka', 'karta', 'blik', 'bitcoin', 'PayPal'));

ALTER TABLE OWNER.PLATNOSC
    ADD FOREIGN KEY (ID_REST)
        REFERENCES OWNER.RESTAURACJA (ID);


----
CREATE SEQUENCE OWNER.SEQ_DODATKI_MENU;
CREATE TABLE OWNER.DODATKI_MENU
(

    ID                INT DEFAULT OWNER.SEQ_DODATKI_MENU.nextval PRIMARY KEY,
    ID_MENU           INT NOT NULL,
    ID_LISTY_DODATKOW INT NOT NULL
);

ALTER TABLE OWNER.DODATKI_MENU
    ADD FOREIGN KEY (ID_MENU)
        REFERENCES OWNER.MENU (ID);

ALTER TABLE OWNER.DODATKI_MENU
    ADD FOREIGN KEY (ID_LISTY_DODATKOW)
        REFERENCES OWNER.LISTA_DODATKOW (ID);

----
CREATE SEQUENCE OWNER.SEQ_PORCJA;
CREATE TABLE OWNER.PORCJA
(

    ID        INT DEFAULT OWNER.SEQ_PORCJA.nextval PRIMARY KEY,
    ID_MENU   INT,
    WIELKOSC  INT,
    JEDNOSTKA VARCHAR(10),
    OPIS      VARCHAR(20) NOT NULL

);

ALTER TABLE OWNER.PORCJA
    ADD CONSTRAINT opis_CONSTRAINT CHECK (opis in ('mały', 'średni', 'duży', 'b.duży', 'wielki'));

ALTER TABLE OWNER.PORCJA
    ADD FOREIGN KEY (ID_MENU)
        REFERENCES OWNER.MENU (ID);

-------------------------------------------------

---SA
GRANT SELECT ON OWNER.MENU TO GUEST;
GRANT SELECT ON OWNER.ADRES TO GUEST;
GRANT SELECT ON OWNER.DODATKI_MENU TO GUEST;
GRANT SELECT ON OWNER.LISTA_DODATKOW TO GUEST;
GRANT SELECT ON OWNER.PLATNOSC TO GUEST;
GRANT SELECT ON OWNER.PORCJA TO GUEST;
GRANT SELECT ON OWNER.RESTAURACJA TO GUEST;

----PRZYKLADY

INSERT INTO OWNER.ADRES (MIEJSCOWOSC, ULICA, NR_LOKALU, KOD)
VALUES ('Gliwice', 'Dworcowa', '10', '44-100');
INSERT INTO OWNER.RESTAURACJA (NAZWA, ID_ADRES, H_OTW, H_ZAM, DOWOZ)
VALUES ('Kebabi', 1, parsedatetime('09:00', 'hh:mm'), parsedatetime('02:00', 'hh:mm'), 1);
INSERT INTO OWNER.MENU (ID_REST, NAZWA_PRODUKTU, CENA)
VALUES (1, 'Kebab na cienkim', 11);
INSERT INTO OWNER.LISTA_DODATKOW (NAZWA)
VALUES ('Ketchup');
INSERT INTO OWNER.DODATKI_MENU (ID_MENU, ID_LISTY_DODATKOW)
VALUES (1, 1);
INSERT INTO OWNER.PLATNOSC (ID_REST, RODZAJ_PLATNOSCI)
VALUES (1, 'gotówka');
INSERT INTO OWNER.PORCJA (ID_MENU, WIELKOSC, JEDNOSTKA, OPIS)
VALUES (1, 300, 'g', 'mały');

